// Generated by CoffeeScript 1.6.1
(function() {
  var SitesHasher;

  SitesHasher = (function() {

    function SitesHasher(shaFunction, scope) {
      this.shaFunction = shaFunction;
      this.scope = scope != null ? scope : null;
      if (this.shaFunction == null) {
        throw "Need a sha function";
      }
    }

    SitesHasher.prototype.generate = function(sites) {
      var data, site, stringifiedData;
      data = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = sites.length; _i < _len; _i++) {
          site = sites[_i];
          _results.push("" + site.url + ": " + (site.tags.sort().join(', ')));
        }
        return _results;
      })();
      stringifiedData = data.sort().join('|');
      return this.shaFunction.apply(this.scope, [stringifiedData]);
    };

    return SitesHasher;

  })();

  if (typeof exports !== 'undefined') {
    module.exports = SitesHasher;
  } else {
    BH.Lib.SitesHasher = SitesHasher;
  }

}).call(this);
